version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vertigo-ui"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/vertigo-backend"
    schedule:
      interval: "daily"
    target-branch: "develop"
