"""test

Revision ID: 061946c3b1b9
Revises: af6f3f264a61
Create Date: 2025-11-27 17:24:39.352680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061946c3b1b9'
down_revision = 'af6f3f264a61'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###

