"""fix main_char table 1

Revision ID: 169f8c125d60
Revises: 38152bdd1639
Create Date: 2025-05-10 21:18:49.166461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169f8c125d60'
down_revision = '38152bdd1639'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

