"""add mal_id fields

Revision ID: 1fea707dfe0d
Revises: 6da91880ce36
Create Date: 2026-02-25 16:11:35.844825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fea707dfe0d'
down_revision = '6da91880ce36'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mal_url', sa.String(length=280), nullable=True))

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mal_url', sa.String(length=280), nullable=True))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mal_url', sa.String(length=280), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1250),
               type_=sa.String(length=3000),
               existing_nullable=True)

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mal_url', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_column('mal_url')
        batch_op.drop_column('mal_id')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1250),
               existing_nullable=True)
        batch_op.drop_column('mal_url')
        batch_op.drop_column('mal_id')

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_column('mal_url')
        batch_op.drop_column('mal_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('mal_url')
        batch_op.drop_column('mal_id')

    # ### end Alembic commands ###

