"""create all remaining fields

Revision ID: 22a968057e40
Revises: 66560b86318b
Create Date: 2024-05-14 10:41:50.111288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a968057e40'
down_revision = '66560b86318b'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_timestamp'), ['timestamp'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_timestamp'), ['timestamp'], unique=False)

    op.create_table('colorist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colorist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colorist_timestamp'), ['timestamp'], unique=False)

    op.create_table('editor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editor_timestamp'), ['timestamp'], unique=False)

    op.create_table('inker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inker_timestamp'), ['timestamp'], unique=False)

    op.create_table('letterer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('letterer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_letterer_timestamp'), ['timestamp'], unique=False)

    op.create_table('penciller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penciller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penciller_timestamp'), ['timestamp'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_timestamp'), ['timestamp'], unique=False)

    op.create_table('writer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writer_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_artist',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'artist_id')
    )
    op.create_table('series_character',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'character_id')
    )
    op.create_table('series_colorist',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('colorist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colorist_id'], ['colorist.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'colorist_id')
    )
    op.create_table('series_editor',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['editor.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'editor_id')
    )
    op.create_table('series_inker',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('inker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inker_id'], ['inker.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'inker_id')
    )
    op.create_table('series_letterer',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('letterer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['letterer_id'], ['letterer.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'letterer_id')
    )
    op.create_table('series_penciller',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('penciller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penciller_id'], ['penciller.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'penciller_id')
    )
    op.create_table('series_team',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'team_id')
    )
    op.create_table('series_writer',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['writer.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'writer_id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('artist')
        batch_op.drop_column('letterer')
        batch_op.drop_column('editor')
        batch_op.drop_column('teams')
        batch_op.drop_column('penciller')
        batch_op.drop_column('colorist')
        batch_op.drop_column('writer')
        batch_op.drop_column('characters')
        batch_op.drop_column('inker')

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inker', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('characters', sa.VARCHAR(length=570), nullable=True))
        batch_op.add_column(sa.Column('writer', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('colorist', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('penciller', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('teams', sa.VARCHAR(length=570), nullable=True))
        batch_op.add_column(sa.Column('editor', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('letterer', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=280), nullable=True))

    op.drop_table('series_writer')
    op.drop_table('series_team')
    op.drop_table('series_penciller')
    op.drop_table('series_letterer')
    op.drop_table('series_inker')
    op.drop_table('series_editor')
    op.drop_table('series_colorist')
    op.drop_table('series_character')
    op.drop_table('series_artist')
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writer_timestamp'))

    op.drop_table('writer')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_timestamp'))

    op.drop_table('team')
    with op.batch_alter_table('penciller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penciller_timestamp'))

    op.drop_table('penciller')
    with op.batch_alter_table('letterer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_letterer_timestamp'))

    op.drop_table('letterer')
    with op.batch_alter_table('inker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inker_timestamp'))

    op.drop_table('inker')
    with op.batch_alter_table('editor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editor_timestamp'))

    op.drop_table('editor')
    with op.batch_alter_table('colorist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colorist_timestamp'))

    op.drop_table('colorist')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_timestamp'))

    op.drop_table('character')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_timestamp'))

    op.drop_table('artist')
    # ### end Alembic commands ###

