"""add last_updated to entities

Revision ID: 271a87f108cd
Revises: 1fea707dfe0d
Create Date: 2026-02-26 11:43:00.731511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271a87f108cd'
down_revision = '1fea707dfe0d'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_character_last_updated'), ['last_updated'], unique=False)

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_creator_last_updated'), ['last_updated'], unique=False)

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_genre_last_updated'), ['last_updated'], unique=False)

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_publisher_last_updated'), ['last_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publisher_last_updated'))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_last_updated'))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_last_updated'))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_last_updated'))
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###

