"""Add price details

Revision ID: 3631a974d537
Revises: a7b4ec9e9a55
Create Date: 2025-01-13 12:23:31.905126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3631a974d537'
down_revision = 'a7b4ec9e9a55'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_price', sa.Float(), nullable=True))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('purchase_cost')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('bought_price')

    # ### end Alembic commands ###

