"""fix main_char table

Revision ID: 38152bdd1639
Revises: dc734e0db459
Create Date: 2025-05-10 21:05:56.392120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38152bdd1639'
down_revision = 'dc734e0db459'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

