"""add notes field for series and issues

Revision ID: 3d392057fa36
Revises: d0f69b8db4bd
Create Date: 2026-06-22 13:03:12.415648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d392057fa36'
down_revision = 'd0f69b8db4bd'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=3000), nullable=True))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=3000), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###

