"""add new fields to issues and entities

Revision ID: 5276db21dcec
Revises: 169f8c125d60
Create Date: 2025-11-27 14:58:40.705116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5276db21dcec'
down_revision = '169f8c125d60'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=280), nullable=True))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=280), nullable=True))

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('cover_date')

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###

