"""refactor genre field v2

Revision ID: 66560b86318b
Revises: 67dd26198fda
Create Date: 2024-04-19 10:09:22.039074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66560b86318b'
down_revision = '67dd26198fda'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

