"""refactor genre field

Revision ID: 67dd26198fda
Revises: e08c37b968b8
Create Date: 2024-04-01 17:25:20.546113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dd26198fda'
down_revision = 'e08c37b968b8'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_genre',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'genre_id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1250), nullable=True))
        batch_op.drop_column('summary')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(length=570), nullable=True))
        batch_op.drop_column('description')

    op.drop_table('series_genre')
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_timestamp'))

    op.drop_table('genre')
    # ### end Alembic commands ###

