"""add support for syncing

Revision ID: 6da91880ce36
Revises: eac88997b160
Create Date: 2026-01-21 01:45:32.256731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da91880ce36'
down_revision = 'eac88997b160'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_records_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_records_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_records_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_issue_last_updated'), ['last_updated'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
        batch_op.create_index(batch_op.f('ix_series_last_updated'), ['last_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_last_updated'))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_last_updated'))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('deleted_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_deleted_records_table_name'))
        batch_op.drop_index(batch_op.f('ix_deleted_records_object_id'))
        batch_op.drop_index(batch_op.f('ix_deleted_records_deleted_at'))

    op.drop_table('deleted_records')
    # ### end Alembic commands ###

