"""add entity selectors to User Model

Revision ID: 742de3916960
Revises: eb1e8aae5d8b
Create Date: 2025-11-30 19:32:24.369952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742de3916960'
down_revision = 'eb1e8aae5d8b'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

