"""switch posts to series

Revision ID: 768fe55b16c8
Revises: a1cf7b63e510
Create Date: 2022-11-05 18:30:47.317727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768fe55b16c8'
down_revision = 'a1cf7b63e510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('publisher', sa.String(length=280), nullable=True),
    sa.Column('genre', sa.String(length=280), nullable=True),
    sa.Column('main_char', sa.String(length=280), nullable=True),
    sa.Column('writer', sa.String(length=280), nullable=True),
    sa.Column('artist', sa.String(length=280), nullable=True),
    sa.Column('editor', sa.String(length=280), nullable=True),
    sa.Column('summary', sa.String(length=570), nullable=True),
    sa.Column('series_format', sa.String(length=100), nullable=True),
    sa.Column('books_count', sa.Integer(), nullable=True),
    sa.Column('read_whole', sa.Integer(), nullable=True),
    sa.Column('have_whole', sa.Integer(), nullable=True),
    sa.Column('dominant_color', sa.String(length=280), nullable=True),
    sa.Column('slug', sa.String(length=280), nullable=True),
    sa.Column('thumbnail', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_timestamp'), 'series', ['timestamp'], unique=False)
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_index('ix_posts_user_id', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('publisher', sa.VARCHAR(length=280), nullable=True),
    sa.Column('writer', sa.VARCHAR(length=280), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=280), nullable=True),
    sa.Column('series_format', sa.VARCHAR(length=280), nullable=True),
    sa.Column('books_count', sa.INTEGER(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=280), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=280), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('main_char', sa.VARCHAR(length=280), nullable=True),
    sa.Column('artist', sa.VARCHAR(length=280), nullable=True),
    sa.Column('editor', sa.VARCHAR(length=280), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=570), nullable=True),
    sa.Column('read_whole', sa.INTEGER(), nullable=True),
    sa.Column('have_whole', sa.INTEGER(), nullable=True),
    sa.Column('dominant_color', sa.VARCHAR(length=280), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_user_id', 'posts', ['user_id'], unique=False)
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.drop_index(op.f('ix_series_timestamp'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
