"""add color fieldo

Revision ID: a1cf7b63e510
Revises: ba4d29bc87b3
Create Date: 2022-11-03 14:45:55.207081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cf7b63e510'
down_revision = 'ba4d29bc87b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dominant_color', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dominant_color')
    # ### end Alembic commands ###
