"""Change to creators

Revision ID: a7b4ec9e9a55
Revises: b9098b0ba83d
Create Date: 2024-12-28 00:41:59.108134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b4ec9e9a55'
down_revision = 'b9098b0ba83d'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_creator',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'creator_id')
    )
    op.drop_table('series_penciller')
    with op.batch_alter_table('letterer', schema=None) as batch_op:
        batch_op.drop_index('ix_letterer_timestamp')

    op.drop_table('letterer')
    op.drop_table('series_artist')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index('ix_artist_timestamp')

    op.drop_table('artist')
    with op.batch_alter_table('colorist', schema=None) as batch_op:
        batch_op.drop_index('ix_colorist_timestamp')

    op.drop_table('colorist')
    op.drop_table('series_editor')
    op.drop_table('series_colorist')
    with op.batch_alter_table('penciller', schema=None) as batch_op:
        batch_op.drop_index('ix_penciller_timestamp')

    op.drop_table('penciller')
    with op.batch_alter_table('editor', schema=None) as batch_op:
        batch_op.drop_index('ix_editor_timestamp')

    op.drop_table('editor')
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.drop_index('ix_writer_timestamp')

    op.drop_table('writer')
    op.drop_table('series_writer')
    op.drop_table('series_letterer')
    with op.batch_alter_table('inker', schema=None) as batch_op:
        batch_op.drop_index('ix_inker_timestamp')

    op.drop_table('inker')
    op.drop_table('series_inker')
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_inker',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('inker_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['inker_id'], ['inker.id'], name='fk_series_inker_inker_id_inker'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_inker_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'inker_id', name='pk_series_inker')
    )
    op.create_table('inker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_inker')
    )
    with op.batch_alter_table('inker', schema=None) as batch_op:
        batch_op.create_index('ix_inker_timestamp', ['timestamp'], unique=False)

    op.create_table('series_letterer',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('letterer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['letterer_id'], ['letterer.id'], name='fk_series_letterer_letterer_id_letterer'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_letterer_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'letterer_id', name='pk_series_letterer')
    )
    op.create_table('series_writer',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('writer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_writer_series_id_series'),
    sa.ForeignKeyConstraint(['writer_id'], ['writer.id'], name='fk_series_writer_writer_id_writer'),
    sa.PrimaryKeyConstraint('series_id', 'writer_id', name='pk_series_writer')
    )
    op.create_table('writer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_writer')
    )
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.create_index('ix_writer_timestamp', ['timestamp'], unique=False)

    op.create_table('editor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_editor')
    )
    with op.batch_alter_table('editor', schema=None) as batch_op:
        batch_op.create_index('ix_editor_timestamp', ['timestamp'], unique=False)

    op.create_table('penciller',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_penciller')
    )
    with op.batch_alter_table('penciller', schema=None) as batch_op:
        batch_op.create_index('ix_penciller_timestamp', ['timestamp'], unique=False)

    op.create_table('series_colorist',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('colorist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['colorist_id'], ['colorist.id'], name='fk_series_colorist_colorist_id_colorist'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_colorist_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'colorist_id', name='pk_series_colorist')
    )
    op.create_table('series_editor',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('editor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['editor.id'], name='fk_series_editor_editor_id_editor'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_editor_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'editor_id', name='pk_series_editor')
    )
    op.create_table('colorist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_colorist')
    )
    with op.batch_alter_table('colorist', schema=None) as batch_op:
        batch_op.create_index('ix_colorist_timestamp', ['timestamp'], unique=False)

    op.create_table('artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_artist')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index('ix_artist_timestamp', ['timestamp'], unique=False)

    op.create_table('series_artist',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='fk_series_artist_artist_id_artist'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_artist_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'artist_id', name='pk_series_artist')
    )
    op.create_table('letterer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_letterer')
    )
    with op.batch_alter_table('letterer', schema=None) as batch_op:
        batch_op.create_index('ix_letterer_timestamp', ['timestamp'], unique=False)

    op.create_table('series_penciller',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('penciller_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['penciller_id'], ['penciller.id'], name='fk_series_penciller_penciller_id_penciller'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_penciller_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'penciller_id', name='pk_series_penciller')
    )
    op.drop_table('series_creator')
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_timestamp'))

    op.drop_table('creator')
    # ### end Alembic commands ###

