"""fix metron id

Revision ID: ae20b3755a05
Revises: f6855e015336
Create Date: 2025-12-30 21:23:26.011257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae20b3755a05'
down_revision = 'f6855e015336'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('metron_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_character_metron_id'))

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.alter_column('metron_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_creator_metron_id'))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('metron_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_issue_metron_id'))

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.alter_column('metron_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_publisher_metron_id'))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('metron_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_series_metron_id'))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_metron_id'), ['metron_id'], unique=False)
        batch_op.alter_column('metron_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publisher_metron_id'), ['metron_id'], unique=False)
        batch_op.alter_column('metron_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_metron_id'), ['metron_id'], unique=False)
        batch_op.alter_column('metron_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_metron_id'), ['metron_id'], unique=False)
        batch_op.alter_column('metron_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_metron_id'), ['metron_id'], unique=False)
        batch_op.alter_column('metron_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###

