"""change issue column names

Revision ID: b9098b0ba83d
Revises: a61737a812d1
Create Date: 2024-07-19 12:19:04.795191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9098b0ba83d'
down_revision = 'a61737a812d1'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_owned', sa.Integer(), nullable=True))
        batch_op.drop_column('have_whole')
        batch_op.drop_column('read_whole')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned_count', sa.Integer(), nullable=True))
        batch_op.drop_column('have_count')

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('have_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('owned_count')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_whole', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('have_whole', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_owned')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###

