"""more series info

Revision ID: ba4d29bc87b3
Revises: 5c2815bb8263
Create Date: 2022-10-29 15:37:28.973014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d29bc87b3'
down_revision = '5c2815bb8263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('main_char', sa.String(length=280), nullable=True))
    op.add_column('posts', sa.Column('artist', sa.String(length=280), nullable=True))
    op.add_column('posts', sa.Column('editor', sa.String(length=280), nullable=True))
    op.add_column('posts', sa.Column('summary', sa.String(length=570), nullable=True))
    op.add_column('posts', sa.Column('read_whole', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('have_whole', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'have_whole')
    op.drop_column('posts', 'read_whole')
    op.drop_column('posts', 'summary')
    op.drop_column('posts', 'editor')
    op.drop_column('posts', 'artist')
    op.drop_column('posts', 'main_char')
    # ### end Alembic commands ###
