"""uniqueness

Revision ID: d0f69b8db4bd
Revises: 271a87f108cd
Create Date: 2026-06-17 17:28:16.820334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f69b8db4bd'
down_revision = '271a87f108cd'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_series_issue_number', ['series_id', 'number'])

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint('uq_series_issue_number', type_='unique')
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###

