"""Merge teams and character

Revision ID: dc734e0db459
Revises: c9ef0ddd7b7a
Create Date: 2025-05-10 20:25:44.323679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc734e0db459'
down_revision = 'c9ef0ddd7b7a'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_character_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_main_character',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('main_character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_character_id'], ['main_character.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'main_character_id')
    )
    op.drop_table('series_team')
    op.drop_table('series_character')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_timestamp')

    op.drop_table('team')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index('ix_character_timestamp')

    op.drop_table('character')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('main_char_type')
        batch_op.drop_column('main_char_id')

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_char_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('main_char_type', sa.VARCHAR(length=50), nullable=True))

    op.create_table('character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_character')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index('ix_character_timestamp', ['timestamp'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_team')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index('ix_team_timestamp', ['timestamp'], unique=False)

    op.create_table('series_character',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fk_series_character_character_id_character'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_character_series_id_series'),
    sa.PrimaryKeyConstraint('series_id', 'character_id', name='pk_series_character')
    )
    op.create_table('series_team',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='fk_series_team_series_id_series'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='fk_series_team_team_id_team'),
    sa.PrimaryKeyConstraint('series_id', 'team_id', name='pk_series_team')
    )
    op.drop_table('series_main_character')
    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_character_timestamp'))

    op.drop_table('main_character')
    # ### end Alembic commands ###

