"""change summary-description+add user rating to issues

Revision ID: e1b833753b38
Revises: 3d392057fa36
Create Date: 2026-06-22 13:21:45.183378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b833753b38'
down_revision = '3d392057fa36'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=570), nullable=True))
        batch_op.add_column(sa.Column('user_rating', sa.Float(), nullable=True))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(length=570), nullable=True))
        batch_op.drop_column('user_rating')
        batch_op.drop_column('description')

    # ### end Alembic commands ###

