"""add slug to entities

Revision ID: e261cf03b489
Revises: f27c3e5f4483
Create Date: 2025-11-27 15:58:38.430820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e261cf03b489'
down_revision = 'f27c3e5f4483'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=280), nullable=True))

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=280), nullable=True))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=280), nullable=True))

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###

