"""rename main_character model to character

Revision ID: f27c3e5f4483
Revises: 5276db21dcec
Create Date: 2025-11-27 15:22:50.140631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27c3e5f4483'
down_revision = '5276db21dcec'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1250), nullable=True),
    sa.Column('thumbnail', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_character',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'character_id')
    )
    op.drop_table('series_main_character')
    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_character_timestamp'))

    op.drop_table('main_character')
    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=280), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1250), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_main_character')
    )
    with op.batch_alter_table('main_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_character_timestamp'), ['timestamp'], unique=False)

    op.create_table('series_main_character',
    sa.Column('series_id', sa.INTEGER(), nullable=False),
    sa.Column('main_character_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['main_character_id'], ['main_character.id'], name=op.f('fk_series_main_character_main_character_id_main_character')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_main_character_series_id_series')),
    sa.PrimaryKeyConstraint('series_id', 'main_character_id', name=op.f('pk_series_main_character'))
    )
    op.drop_table('series_character')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_timestamp'))

    op.drop_table('character')
    # ### end Alembic commands ###

