"""add metron info

Revision ID: f6855e015336
Revises: 9c916575e1e8
Create Date: 2025-12-30 20:01:15.204734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6855e015336'
down_revision = '9c916575e1e8'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metron_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metron_url', sa.String(length=280), nullable=True))
        batch_op.create_index(batch_op.f('ix_character_metron_id'), ['metron_id'], unique=False)

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metron_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metron_url', sa.String(length=280), nullable=True))
        batch_op.create_index(batch_op.f('ix_creator_metron_id'), ['metron_id'], unique=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metron_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metron_url', sa.String(length=280), nullable=True))
        batch_op.create_index(batch_op.f('ix_issue_metron_id'), ['metron_id'], unique=False)

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metron_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metron_url', sa.String(length=280), nullable=True))
        batch_op.create_index(batch_op.f('ix_publisher_metron_id'), ['metron_id'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metron_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metron_url', sa.String(length=280), nullable=True))
        batch_op.create_index(batch_op.f('ix_series_metron_id'), ['metron_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_metron_id'))
        batch_op.drop_column('metron_url')
        batch_op.drop_column('metron_id')

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publisher_metron_id'))
        batch_op.drop_column('metron_url')
        batch_op.drop_column('metron_id')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_metron_id'))
        batch_op.drop_column('metron_url')
        batch_op.drop_column('metron_id')

    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_metron_id'))
        batch_op.drop_column('metron_url')
        batch_op.drop_column('metron_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_metron_id'))
        batch_op.drop_column('metron_url')
        batch_op.drop_column('metron_id')

    # ### end Alembic commands ###

